### ISSUE TITLE
Golang Reflect 系列一 - 和 deepcopy 有关的 | hzSomthing

### ISSUE THREAD

**Issue by hedzr** [hedzr/hedzr.github.io#27]
https://hedzr.github.io/golang/reflect/golang-reflect-1/ 

 Golang 反射之一，deepcopy相关的内容…

**Comment by gaunthan** [comment]
请教下unsafe pointer方式的缺点都有哪些？

**Comment by hedzr** [comment]
> @gaunthan
> 请教下unsafe pointer方式的缺点都有哪些？

至少有两点：
- golang 发行版本不同时，unsafe pointer 所解释的目标可能会因为底层结构的不同而失效
- 不同的 CPU Arch 或者 OS 中，指向的目标可能因为字长、对齐的关系而是错的

**Comment by gaunthan** [comment]
您的来信我已收到，我会尽快回复。
