### ISSUE TITLE
21央美，有人到来 | hzSomthing

### ISSUE THREAD

**Issue by hedzr** [hedzr/hedzr.github.io#69]
https://hedzr.com/life-style/art/cafa-sb-coming/ 

 女儿拿到了通知书…

**Comment by Vinluo** [comment]
Just browsing your blog.
It's a pleasure to hear such good news, congratulations!

**Comment by Vinluo** [comment]
恭喜您啦，刚刚可能是输入法问题，没法直接评论输入中文。顺带一提，您博客的评论框在输入时的字体颜色和背景色都是白色，还挺影响体验。

**Comment by hedzr** [comment]
应该是 gittalk 组件 css 适配问题，回头试试解决

**Comment by hedzr** [comment]
> @Vinluo
> Just browsing your blog.
> It's a pleasure to hear such good news, congratulations!

thx a lot

**Comment by hedzr** [comment]
> 顺带一提，您博客的评论框在输入时的字体颜色和背景色都是白色，还挺影响体验。

unskilled patch made
